/** Short scenario framing shown above isolated block demos. */
export const DEMO_INTROS: Record<string, string> = {
  "true-false":
    "During annual security training, decide whether this statement about phishing is accurate.",
  quiz: "A password-reset email arrives while you are on a public network. Pick the safest first step.",
  "fill-in-the-blanks": "Complete the reporting procedure using the approved words from policy.",
  "mark-the-words": "Select every sensitive term learners must never share according to policy.",
  "drag-the-words": "Drag the approved response into the sentence about suspicious mail.",
  "drag-and-drop": "Sort each channel into the correct risk category before submitting.",
  "assessment-sequence": "Complete both checks to finish the phishing module gate.",
  scenario:
    "You are triaging your inbox before a vendor call. Read the situation, then decide your next move.",
  reflection: "Before you close the module, note one habit you will change this week.",
  "interactive-book": "Use this handbook to review reporting steps before the knowledge check.",
  "slide-deck": "A three-slide briefing on phishing red flags and how to report them.",
  "branching-scenario":
    "A customer calls about a suspicious charge. Choose responses that build trust and follow policy.",
  accordion: "Quick reference for the most common security questions from new hires.",
  summary: "Build the incident-response summary by selecting only the correct policy statements.",
  "memory-game": "Match each security control with its plain-language description.",
  video: "Watch the two-minute briefing, then continue to the timed knowledge check.",
  "interactive-video": "Pause points in the briefing verify key safety rules before you move on.",
  embed: "Sandboxed iframe for approved third-party tools. Allowlist hosts in production course config.",
  chart: "Quarterly incident categories reported to the security operations team.",
  table: "Keep these escalation contacts handy during an active incident.",
  timeline: "How our phishing response playbook evolved after the last tabletop exercise.",
  flashcards: "Flip through core vocabulary before the module quiz.",
  "dialog-cards": "Practice the phrases you will use when coaching colleagues on reporting.",
  questionnaire: "Help us improve the next security awareness cohort.",
  essay: "A vendor emails an urgent invoice change. Explain how you would verify the request.",
  "combination-lock": "Enter the demo vault code from the onboarding briefing (training use only).",
  crossword: "Two short answers cross on the letter A — MFA across and API down.",
  "word-search": "Find the security terms hidden in the grid.",
  "game-map": "Tour the office and complete a check at each stop before the exit briefing.",
  "image-hotspots": "Explore the floor plan — tap each marker to review egress and workstation rules.",
  "image-juxtaposition": "Compare a compliant workspace with one that violates clean-desk policy.",
  "qr-content": "Scan the QR code on the poster to unlock the optional deep-dive checklist.",
  "text-and-heading": "Introduce a policy section with a heading and supporting paragraph.",
  page: "Pages group related content inside an interactive book or compound lesson.",
  slide: "Each slide is a focused beat inside a deck — context, action, then a check.",
  "timed-cue": "Timed cues pause playback until learners acknowledge policy at key moments.",
  image: "Use labeled diagrams when text alone cannot convey layout or location.",
  "image-pairing": "Match each piece of PPE with its label before the warehouse walkthrough.",
  "image-sequencing": "Put the incident-reporting screenshots in the correct order.",
  "arithmetic-quiz": "Quick handoff math for the shift log — enter each answer before continuing.",
  "find-hotspot": "On the floor plan, locate the single blocked aisle that violates egress policy.",
  "find-multiple-hotspots": "Mark every trip and spill hazard on the floor plan. Avoid decoy areas.",
  "information-wall": "Searchable panels for policies learners revisit during the course.",
  "parallax-slideshow": "Scroll through how the security program matured over three releases.",
  "image-slider": "Drag to compare a cluttered desk with a clean-desk compliant setup.",
  "image-sequence": "Step through the incident-reporting flow frame by frame.",
  collage: "Combine site layout and team contacts in one visual panel grid.",
  "audio-recorder": "Practice the approved verbal escalation script for your region.",
  "advent-calendar": "Open one door per day during December security awareness month.",
  "branch-node": "Each branch node holds narrative content, choices, and optional terminal checks.",
  "branch-choice": "Choices route learners to different nodes — optional scoreWeight affects path score.",
  "map-stage": "Stages hold the content shown when learners visit a point on the game map.",
  "map-exit": "Exits link map stages together, similar to branch choices in a spatial layout.",
  "knowledge-check":
    "Legacy alias for Quiz — same scoring behavior. Prefer Quiz in new projects.",
};
