export {
  assertTrackingSinkConfig,
  buildCourseStartedEvent,
  createCourseStartedFlightScope,
  emitCourseStarted,
  emitCourseStartedPipelineOnly,
  emitCourseStartedToTracking,
  emitCourseStartedToTrackingOnly,
  emitPendingCourseStarted,
  isCourseStartedSinkSettled,
  isTrackingActive,
  resetCourseStartedTrackingFlightForTests,
  resetCourseStartedTrackingFlights,
  type CourseStartedEmitOpts,
  type CourseStartedEmitResult,
  type CourseStartedFlightScope,
} from "./emit";
