/** H5P-aligned capability tiers (A–E) for block-catalog.v3.json. See docs/project/h5p-capability-map.md */
export const BLOCK_TIER_BY_TYPE: Record<string, "A" | "B" | "C" | "D" | "E"> = {
  AssessmentSequence: "A",
  InteractiveBook: "A",
  SlideDeck: "A",
  InteractiveVideo: "A",
  BranchingScenario: "A",
  Page: "A",
  GameMap: "A",
  Quiz: "B",
  TrueFalse: "B",
  FillInTheBlanks: "B",
  DragAndDrop: "B",
  DragTheWords: "B",
  MarkTheWords: "B",
  Summary: "B",
  ArithmeticQuiz: "B",
  Essay: "B",
  Questionnaire: "B",
  ImageHotspots: "C",
  FindHotspot: "C",
  FindMultipleHotspots: "C",
  ImageSlider: "C",
  ImageJuxtaposition: "C",
  ImageSequence: "C",
  Collage: "C",
  ImagePairing: "C",
  ImageSequencing: "C",
  MemoryGame: "C",
  Embed: "C",
  Chart: "C",
  Accordion: "D",
  DialogCards: "D",
  Flashcards: "D",
  Timeline: "D",
  Table: "D",
  InformationWall: "D",
  AudioRecorder: "D",
  ParallaxSlideshow: "D",
  Crossword: "E",
  WordSearch: "E",
  CombinationLock: "E",
  QrContent: "E",
  AdventCalendar: "E",
};

export function tierForBlockType(type: string): "A" | "B" | "C" | "D" | "E" | undefined {
  if (type === "KnowledgeCheck") return BLOCK_TIER_BY_TYPE.Quiz;
  return BLOCK_TIER_BY_TYPE[type];
}
