import {
  ASSESSMENT_SEQUENCE_ALLOWED_CHILD_TYPES,
  SINGLE_CHOICE_SET_ALLOWED_CHILD_TYPES,
  BRANCHING_SCENARIO_ALLOWED_CHILD_TYPES,
  BRANCH_NODE_ALLOWED_CHILD_TYPES,
  GAME_MAP_ALLOWED_CHILD_TYPES,
  MAP_STAGE_ALLOWED_CHILD_TYPES,
  INTERACTIVE_BOOK_ALLOWED_CHILD_TYPES,
  INTERACTIVE_VIDEO_ALLOWED_CHILD_TYPES,
  PAGE_ALLOWED_CHILD_TYPES,
  SLIDE_ALLOWED_CHILD_TYPES,
  SLIDE_DECK_ALLOWED_CHILD_TYPES,
  TIMED_CUE_ALLOWED_CHILD_TYPES,
  COMPOUND_MAX_NESTING_DEPTH,
} from "@lessonkit/core";
import type { BlockCatalogEntryV2 } from "./blockCatalog";

const COMPOUND_PARENTS = [
  "Lesson",
  "Page",
  "InteractiveBook",
  "Slide",
  "SlideDeck",
  "TimedCue",
  "InteractiveVideo",
  "AssessmentSequence",
  "SingleChoiceSet",
  "BranchingScenario",
  "BranchNode",
  "GameMap",
  "MapStage",
] as const;

function extendParents(entry: BlockCatalogEntryV2): BlockCatalogEntryV2 {
  if (!entry.parentConstraints?.length) return entry;
  const merged = new Set([...entry.parentConstraints, ...COMPOUND_PARENTS]);
  return { ...entry, parentConstraints: [...merged] };
}

const assessmentBehaviourProps = [
  { name: "enableRetry", type: "boolean", required: false, description: "Allow retry after completion." },
  { name: "enableSolutionsButton", type: "boolean", required: false, description: "Show solution control." },
  { name: "autoCheck", type: "boolean", required: false, description: "Check answers automatically when possible." },
  { name: "passingScore", type: "number", required: false, description: "Minimum score to pass." },
];

export const v3CompoundAndContentEntries = [
  {
    type: "Text",
    category: "content" as const,
    description: "Paragraph text content.",
    props: [
      { name: "blockId", type: "BlockId", required: false, description: "Stable block id." },
      { name: "children", type: "ReactNode", required: true, description: "Text body." },
    ],
    requiredIds: [],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "p", ariaLabel: "Text", keyboard: "N/A", notes: "Semantic paragraph." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Inherits theme." },
    telemetry: { emits: [] },
  },
  {
    type: "Heading",
    category: "content" as const,
    description: "Heading levels 1–3.",
    props: [
      { name: "blockId", type: "BlockId", required: false, description: "Stable block id." },
      { name: "level", type: "1 | 2 | 3", required: true, description: "Heading level." },
      { name: "children", type: "ReactNode", required: true, description: "Heading text." },
    ],
    requiredIds: [],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "h1-h3", ariaLabel: "Heading", keyboard: "N/A", notes: "Use one level per outline." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Inherits theme." },
    telemetry: { emits: [] },
  },
  {
    type: "Image",
    category: "content" as const,
    description: "Image with required alt text.",
    props: [
      { name: "blockId", type: "BlockId", required: false, description: "Stable block id." },
      { name: "src", type: "string", required: true, description: "Image URL." },
      { name: "alt", type: "string", required: true, description: "Alt text." },
    ],
    requiredIds: [],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "img", ariaLabel: "Image", keyboard: "N/A", notes: "Requires alt." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Responsive max-width." },
    telemetry: { emits: [] },
  },
  {
    type: "Video",
    category: "content" as const,
    description: "Self-hosted video with native controls and optional captions.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "src", type: "string", required: true, description: "Video URL." },
      { name: "poster", type: "string", required: false, description: "Poster image URL." },
      { name: "captions", type: "string", required: false, description: "WebVTT captions URL." },
      { name: "title", type: "string", required: false, description: "Accessible title." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "video", ariaLabel: "Video", keyboard: "Native video controls.", notes: "No autoplay with sound." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Responsive video." },
    telemetry: { emits: [] },
  },
  {
    type: "Page",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.Column",
    h5pAlias: "Column",
    description: "Column layout container (H5P Column / Page).",
    allowedChildTypes: [...PAGE_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.Page,
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "title", type: "string", required: false, description: "Page title." },
      { name: "children", type: "ReactNode", required: true, description: "Page content." },
    ],
    requiredIds: [],
    optionalIds: ["blockId"],
    parentConstraints: ["Lesson", "InteractiveBook"],
    a11y: { element: "section", ariaLabel: "Page", keyboard: "N/A", notes: "H5P Column equivalent." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Container." },
    telemetry: { emits: ["compound_page_viewed"], requiresActiveLesson: true },
  },
  {
    type: "InteractiveBook",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.InteractiveBook",
    h5pAlias: "Interactive Book",
    description: "Multi-page book with chapter navigation.",
    allowedChildTypes: [...INTERACTIVE_BOOK_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.InteractiveBook,
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "title", type: "string", required: true, description: "Book title." },
      { name: "showBookScore", type: "boolean", required: false, description: "Show aggregate score." },
      { name: "children", type: "Page[]", required: true, description: "Page chapters." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: ["Lesson"],
    a11y: {
      element: "section",
      ariaLabel: "Interactive book",
      keyboard: "Previous/Next chapter navigation.",
      notes: "H5P Interactive Book equivalent.",
    },
    theming: { surface: "global-inherit" as const, stylingNotes: "Book chrome." },
    telemetry: { emits: ["book_page_viewed"], requiresActiveLesson: true },
  },
  {
    type: "Slide",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.CoursePresentation",
    h5pAlias: "Course Presentation slide",
    description: "Single slide row in a SlideDeck. Supports Video, Summary, and 1.4 blocks.",
    allowedChildTypes: [...SLIDE_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.Slide,
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "title", type: "string", required: false, description: "Slide title." },
      { name: "children", type: "ReactNode", required: true, description: "Slide content." },
    ],
    requiredIds: [],
    optionalIds: ["blockId"],
    parentConstraints: ["SlideDeck"],
    a11y: { element: "section", ariaLabel: "Slide", keyboard: "N/A", notes: "H5P Course Presentation slide row." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Container." },
    telemetry: { emits: ["compound_page_viewed"], requiresActiveLesson: true },
  },
  {
    type: "SlideDeck",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.CoursePresentation",
    h5pAlias: "Course Presentation",
    description: "Multi-slide presentation with keyboard navigation.",
    allowedChildTypes: [...SLIDE_DECK_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.SlideDeck,
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "title", type: "string", required: true, description: "Deck title." },
      { name: "showDeckScore", type: "boolean", required: false, description: "Show aggregate score." },
      { name: "children", type: "Slide[]", required: true, description: "Slides." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: ["Lesson"],
    a11y: {
      element: "section",
      ariaLabel: "Slide deck",
      keyboard: "Arrow keys, Home, End, Previous/Next slide buttons.",
      notes: "H5P Course Presentation equivalent.",
    },
    theming: { surface: "global-inherit" as const, stylingNotes: "Deck chrome." },
    telemetry: { emits: ["slide_viewed"], requiresActiveLesson: true },
  },
  {
    type: "TimedCue",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.InteractiveVideo",
    h5pAlias: "Interactive Video timed cue",
    description: "Timed overlay cue within InteractiveVideo.",
    allowedChildTypes: [...TIMED_CUE_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.TimedCue,
    props: [
      { name: "atSeconds", type: "number", required: true, description: "Cue time in seconds." },
      { name: "label", type: "string", required: false, description: "Cue label." },
      { name: "mustComplete", type: "boolean", required: false, description: "Block seek until completed." },
      { name: "children", type: "ReactNode", required: true, description: "Single allowed child block." },
    ],
    requiredIds: [],
    parentConstraints: ["InteractiveVideo"],
    a11y: { element: "dialog", ariaLabel: "Timed cue", keyboard: "Focus moves to overlay content.", notes: "Pauses parent video." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Overlay panel." },
    telemetry: { emits: [] },
  },
  {
    type: "InteractiveVideo",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.InteractiveVideo",
    h5pAlias: "Interactive Video",
    description: "Video with timed interaction overlays.",
    allowedChildTypes: [...INTERACTIVE_VIDEO_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.InteractiveVideo,
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "title", type: "string", required: true, description: "Video title." },
      { name: "src", type: "string", required: true, description: "Video URL." },
      { name: "poster", type: "string", required: false, description: "Poster image." },
      { name: "captions", type: "string", required: false, description: "WebVTT captions." },
      { name: "showVideoScore", type: "boolean", required: false, description: "Show aggregate score." },
      { name: "children", type: "TimedCue[]", required: true, description: "Timed cues." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: ["Lesson"],
    a11y: {
      element: "section",
      ariaLabel: "Interactive video",
      keyboard: "Native video controls; overlay interactions when paused.",
      notes: "H5P Interactive Video equivalent.",
    },
    theming: { surface: "global-inherit" as const, stylingNotes: "Video + overlay." },
    telemetry: { emits: ["video_cue_reached", "video_segment_completed"], requiresActiveLesson: true },
  },
  {
    type: "BranchNode",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.BranchingScenario",
    h5pAlias: "Branching Scenario node",
    description: "Graph node in a BranchingScenario with content and choices.",
    allowedChildTypes: [...BRANCH_NODE_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.BranchNode,
    props: [
      { name: "nodeId", type: "string", required: true, description: "Unique node id within the scenario." },
      { name: "title", type: "string", required: false, description: "Node title." },
      { name: "terminal", type: "boolean", required: false, description: "End state node." },
      { name: "children", type: "ReactNode", required: true, description: "Content and BranchChoice controls." },
    ],
    requiredIds: [],
    parentConstraints: ["BranchingScenario"],
    a11y: { element: "section", ariaLabel: "Branch node", keyboard: "Branch choices are buttons.", notes: "H5P Branching Scenario node." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Node panel." },
    telemetry: { emits: ["branch_node_viewed"], requiresActiveLesson: true },
  },
  {
    type: "BranchChoice",
    category: "content" as const,
    h5pMachineName: "H5P.BranchingScenario",
    h5pAlias: "Branching Scenario choice",
    description: "Transition control linking to a target BranchNode.",
    props: [
      { name: "label", type: "string", required: true, description: "Choice label." },
      { name: "targetNodeId", type: "string", required: true, description: "Target node id." },
      { name: "scoreWeight", type: "number", required: false, description: "Optional choice score weight." },
      { name: "disabled", type: "boolean", required: false, description: "Disable choice." },
    ],
    requiredIds: [],
    parentConstraints: ["BranchNode"],
    a11y: { element: "button", ariaLabel: "Branch choice", keyboard: "Activate to follow branch.", notes: "Radio group pattern." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Choice button." },
    telemetry: { emits: ["branch_selected"], requiresActiveLesson: true },
  },
  {
    type: "BranchingScenario",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.BranchingScenario",
    h5pAlias: "Branching Scenario",
    description: "Graph-based branching narrative with scored paths.",
    allowedChildTypes: [...BRANCHING_SCENARIO_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.BranchingScenario,
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "title", type: "string", required: true, description: "Scenario title." },
      { name: "startNodeId", type: "string", required: true, description: "Entry node id." },
      { name: "showPathScore", type: "boolean", required: false, description: "Show visited-path score." },
      { name: "showPathRecap", type: "boolean", required: false, description: "Show path recap on terminal nodes." },
      { name: "children", type: "BranchNode[]", required: true, description: "Branch nodes." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: ["Lesson"],
    a11y: {
      element: "section",
      ariaLabel: "Branching scenario",
      keyboard: "Branch choices; assessments in nodes.",
      notes: "H5P Branching Scenario equivalent.",
    },
    theming: { surface: "global-inherit" as const, stylingNotes: "Scenario chrome." },
    telemetry: { emits: ["branch_node_viewed", "branch_selected"], requiresActiveLesson: true },
  },
  {
    type: "Embed",
    category: "content" as const,
    h5pMachineName: "H5P.IFrameEmbed",
    h5pAlias: "Iframe Embedder",
    description: "Sandboxed iframe embed with restrictive defaults.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "src", type: "string", required: true, description: "Embed URL." },
      { name: "title", type: "string", required: true, description: "Accessible title." },
      { name: "allow", type: "string", required: false, description: "Extra sandbox allow tokens." },
      { name: "aspectRatio", type: "string", required: false, description: "CSS aspect-ratio." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "iframe", ariaLabel: "Embedded content", keyboard: "Focus enters iframe.", notes: "Sandboxed; opt-in allow list." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Responsive iframe." },
    telemetry: { emits: ["interaction"] },
  },
  {
    type: "Chart",
    category: "content" as const,
    h5pMachineName: "H5P.Chart",
    h5pAlias: "Chart",
    description: "Simple bar or pie chart with accessible data table.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "type", type: "bar | pie", required: true, description: "Chart type." },
      { name: "data", type: "ChartDatum[]", required: true, description: "Chart data." },
      { name: "title", type: "string", required: false, description: "Chart title." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "figure", ariaLabel: "Chart", keyboard: "Data table fallback.", notes: "Table exposes values to screen readers." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Simple SVG/CSS chart." },
    telemetry: { emits: ["interaction"] },
  },
  {
    type: "Questionnaire",
    category: "content" as const,
    h5pMachineName: "H5P.Questionnaire",
    h5pAlias: "Questionnaire",
    description: "Unscored multi-field survey.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "fields", type: "QuestionnaireField[]", required: true, description: "Form fields." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "form", ariaLabel: "Questionnaire", keyboard: "Tab through fields.", notes: "Unscored survey." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Form layout." },
    telemetry: { emits: ["questionnaire_submitted"], requiresActiveLesson: true },
  },
  {
    type: "MemoryGame",
    category: "content" as const,
    h5pMachineName: "H5P.MemoryGame",
    h5pAlias: "Memory Game",
    description: "Card flip memory matching game.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "pairs", type: "MemoryPair[]", required: true, description: "Card pairs." },
      { name: "selfScore", type: "boolean", required: false, description: "Optional self-score mode." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Memory game", keyboard: "Flip cards with buttons.", notes: "Reduced motion safe." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Card grid." },
    telemetry: { emits: ["memory_card_flipped"] },
  },
  {
    type: "InformationWall",
    category: "content" as const,
    h5pMachineName: "H5P.InformationWall",
    h5pAlias: "Information Wall",
    description: "Searchable information panels.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "panels", type: "InformationPanel[]", required: true, description: "Content panels." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Information wall", keyboard: "Search and browse panels.", notes: "Filterable grid." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Panel grid." },
    telemetry: { emits: ["information_wall_search"] },
  },
  {
    type: "ParallaxSlideshow",
    category: "content" as const,
    h5pMachineName: "H5P.ImpressivePresentation",
    h5pAlias: "Slideshow (parallax)",
    description: "Slideshow with parallax; static fallback when reduced motion.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "slides", type: "ParallaxSlide[]", required: true, description: "Slides." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Slideshow", keyboard: "Previous/next slide.", notes: "prefers-reduced-motion fallback." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Slide deck." },
    telemetry: { emits: ["parallax_slide_viewed"] },
  },
  {
    type: "Accordion",
    category: "content" as const,
    h5pMachineName: "H5P.Accordion",
    h5pAlias: "Accordion",
    description: "Expandable sections.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "sections", type: "AccordionSection[]", required: true, description: "Sections." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Accordion", keyboard: "Button toggles sections.", notes: "No nested accordions." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Disclosure pattern." },
    telemetry: { emits: ["accordion_section_toggled"] },
  },
  {
    type: "DialogCards",
    category: "content" as const,
    h5pMachineName: "H5P.Dialogcards",
    h5pAlias: "Dialog Cards",
    description: "Flip cards with front/back text.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "cards", type: "DialogCard[]", required: true, description: "Cards." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Dialog cards", keyboard: "Flip and navigate cards.", notes: "Reduced motion safe." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Card flip." },
    telemetry: { emits: [] },
  },
  {
    type: "Flashcards",
    category: "content" as const,
    h5pMachineName: "H5P.Flashcards",
    h5pAlias: "Flashcards",
    description: "Study flashcards with optional self-score.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "cards", type: "Flashcard[]", required: true, description: "Cards." },
      { name: "selfScore", type: "boolean", required: false, description: "Self-score mode." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Flashcards", keyboard: "Flip and next.", notes: "Not LMS-scored by default." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Study mode." },
    telemetry: { emits: ["flashcard_flipped"] },
  },
  {
    type: "ImageHotspots",
    category: "content" as const,
    h5pMachineName: "H5P.ImageHotspots",
    h5pAlias: "Image Hotspots",
    description: "Image with clickable hotspot popovers.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "src", type: "string", required: true, description: "Image URL." },
      { name: "alt", type: "string", required: true, description: "Alt text." },
      { name: "hotspots", type: "HotspotSpec[]", required: true, description: "Hotspots." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Image hotspots", keyboard: "Buttons on image.", notes: "Popover dialog." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Positioned hotspots." },
    telemetry: { emits: ["hotspot_opened"] },
  },
  {
    type: "ImageSlider",
    category: "content" as const,
    h5pMachineName: "H5P.ImageSlider",
    h5pAlias: "Image Slider",
    description: "Carousel of images.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "slides", type: "ImageSlide[]", required: true, description: "Slides." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: {
      element: "section",
      ariaLabel: "Image slider",
      keyboard: "Arrow keys, swipe/drag, or Previous/Next buttons.",
      notes: "Focusable section; horizontal drag advances slides.",
    },
    theming: { surface: "global-inherit" as const, stylingNotes: "Slider." },
    telemetry: { emits: ["image_slider_changed"] },
  },
  {
    type: "FindHotspot",
    category: "assessment" as const,
    assessmentContract: true as const,
    h5pMachineName: "H5P.ImageHotspotQuestion",
    h5pAlias: "Find the Hotspot",
    description: "Select the correct region on an image.",
    props: [
      { name: "checkId", type: "CheckId", required: true, description: "Stable check id." },
      { name: "src", type: "string", required: true, description: "Image URL." },
      { name: "alt", type: "string", required: true, description: "Alt text." },
      { name: "targets", type: "HotspotTarget[]", required: true, description: "Targets." },
      { name: "correctTargetId", type: "string", required: true, description: "Correct target id." },
      ...assessmentBehaviourProps,
    ],
    requiredIds: ["checkId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Find the hotspot", keyboard: "Select target buttons.", notes: "Scored." },
    theming: {
      surface: "global-inherit" as const,
      dataAttributes: ["data-lk-check-id"],
      stylingNotes: "Uses data-lk-check-id; Check is pinned in .lk-find-hotspot-toolbar overlay.",
    },
    telemetry: { emits: ["assessment_answered", "assessment_completed"], requiresActiveLesson: true },
  },
  {
    type: "FindMultipleHotspots",
    category: "assessment" as const,
    assessmentContract: true as const,
    h5pMachineName: "H5P.ImageMultipleHotspotQuestion",
    h5pAlias: "Find Multiple Hotspots",
    description: "Select all correct regions on an image.",
    props: [
      { name: "checkId", type: "CheckId", required: true, description: "Stable check id." },
      { name: "src", type: "string", required: true, description: "Image URL." },
      { name: "alt", type: "string", required: true, description: "Alt text." },
      { name: "targets", type: "HotspotTarget[]", required: true, description: "Targets." },
      { name: "correctTargetIds", type: "string[]", required: true, description: "Correct target ids." },
      ...assessmentBehaviourProps,
    ],
    requiredIds: ["checkId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Find multiple hotspots", keyboard: "Toggle targets.", notes: "Scored." },
    theming: { surface: "global-inherit" as const, dataAttributes: ["data-lk-check-id"], stylingNotes: "Uses data-lk-check-id." },
    telemetry: { emits: ["assessment_answered", "assessment_completed"], requiresActiveLesson: true },
  },
  {
    type: "Table",
    category: "content" as const,
    h5pMachineName: "H5P.Table",
    h5pAlias: "Table",
    description: "Rich text table with caption.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "caption", type: "string", required: false, description: "Table caption." },
      { name: "headers", type: "string[]", required: true, description: "Column headers." },
      { name: "rows", type: "string[][]", required: true, description: "Table rows." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "table", ariaLabel: "Table", keyboard: "N/A", notes: "Semantic table." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Responsive scroll." },
    telemetry: { emits: [] },
  },
  {
    type: "ImageJuxtaposition",
    category: "content" as const,
    h5pMachineName: "H5P.ImageJuxtaposition",
    h5pAlias: "Image Juxtaposition",
    description: "Before/after image comparison slider.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "beforeSrc", type: "string", required: true, description: "Before image URL." },
      { name: "afterSrc", type: "string", required: true, description: "After image URL." },
      { name: "beforeAlt", type: "string", required: true, description: "Before alt text." },
      { name: "afterAlt", type: "string", required: true, description: "After alt text." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Image juxtaposition", keyboard: "Range slider.", notes: "Before/after." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Overlay slider." },
    telemetry: { emits: ["image_juxtaposition_changed"] },
  },
  {
    type: "Timeline",
    category: "content" as const,
    h5pMachineName: "H5P.Timeline",
    h5pAlias: "Timeline",
    description: "Vertical timeline of events.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "events", type: "TimelineEvent[]", required: true, description: "Timeline events." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Timeline", keyboard: "Focus events.", notes: "Ordered list." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Vertical timeline." },
    telemetry: { emits: ["timeline_event_viewed"] },
  },
  {
    type: "ImageSequence",
    category: "content" as const,
    h5pMachineName: "H5P.Agamotto",
    h5pAlias: "Agamotto (Image Blender)",
    description: "Progressive image sequence blend.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "frames", type: "SequenceFrame[]", required: true, description: "Sequence frames." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Image sequence", keyboard: "Slider or step buttons.", notes: "Reduced motion uses steps." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Blend slider." },
    telemetry: { emits: ["image_sequence_changed"] },
  },
  {
    type: "Collage",
    category: "content" as const,
    h5pMachineName: "H5P.Collage",
    h5pAlias: "Collage",
    description: "Multi-image grid collage.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "columns", type: "number", required: false, description: "Grid columns." },
      { name: "cells", type: "CollageCell[]", required: true, description: "Collage cells." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Collage", keyboard: "N/A", notes: "Figure per cell." },
    theming: { surface: "global-inherit" as const, stylingNotes: "CSS grid." },
    telemetry: { emits: [] },
  },
  {
    type: "AudioRecorder",
    category: "content" as const,
    h5pMachineName: "H5P.AudioRecorder",
    h5pAlias: "Audio Recorder",
    description: "Learner audio recording (client-only storage).",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "maxDurationSeconds", type: "number", required: false, description: "Max recording length." },
      { name: "consentLabel", type: "string", required: false, description: "Consent checkbox label." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Audio recorder", keyboard: "Record controls.", notes: "Consent required." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Recorder UI." },
    telemetry: { emits: ["audio_recording_started", "audio_recording_completed"] },
  },
  {
    type: "CombinationLock",
    category: "assessment" as const,
    assessmentContract: true as const,
    h5pMachineName: "H5P.CombinationLock",
    h5pAlias: "Combination Lock",
    description: "Enter a digit combination to unlock.",
    props: [
      { name: "checkId", type: "CheckId", required: true, description: "Stable check id." },
      { name: "combination", type: "string", required: true, description: "Correct combination." },
      { name: "label", type: "string", required: false, description: "Prompt label." },
      ...assessmentBehaviourProps,
    ],
    requiredIds: ["checkId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: {
      element: "section",
      ariaLabel: "Combination lock",
      keyboard: "Digit inputs; auto-advance on entry.",
      notes: "Scored; select-all on focus.",
    },
    theming: {
      surface: "global-inherit" as const,
      dataAttributes: ["data-lk-check-id"],
      stylingNotes: "Uses .lk-combination-lock-digit with focus styling.",
    },
    telemetry: { emits: ["assessment_answered", "assessment_completed"], requiresActiveLesson: true },
  },
  {
    type: "QrContent",
    category: "content" as const,
    h5pMachineName: "H5P.KewArCode",
    h5pAlias: "KewAr Code",
    description: "QR code with revealable hidden content.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "payload", type: "string", required: true, description: "QR payload URL or text." },
      { name: "title", type: "string", required: false, description: "Block title." },
      { name: "hiddenTitle", type: "string", required: false, description: "Revealed title." },
      { name: "hiddenBody", type: "string", required: false, description: "Revealed body." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "QR content", keyboard: "Reveal button.", notes: "Simulated scan." },
    theming: { surface: "global-inherit" as const, stylingNotes: "QR display." },
    telemetry: { emits: ["qr_content_revealed"] },
  },
  {
    type: "Crossword",
    category: "assessment" as const,
    assessmentContract: true as const,
    h5pMachineName: "H5P.Crossword",
    h5pAlias: "Crossword",
    description: "Crossword puzzle grid.",
    props: [
      { name: "checkId", type: "CheckId", required: true, description: "Stable check id." },
      { name: "rows", type: "number", required: true, description: "Grid rows." },
      { name: "cols", type: "number", required: true, description: "Grid columns." },
      { name: "entries", type: "CrosswordEntry[]", required: true, description: "Clues and answers." },
      ...assessmentBehaviourProps,
    ],
    requiredIds: ["checkId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Crossword", keyboard: "Grid navigation.", notes: "Scored." },
    theming: { surface: "global-inherit" as const, dataAttributes: ["data-lk-check-id"], stylingNotes: "Uses data-lk-check-id." },
    telemetry: { emits: ["assessment_answered", "assessment_completed"], requiresActiveLesson: true },
  },
  {
    type: "WordSearch",
    category: "assessment" as const,
    assessmentContract: true as const,
    h5pMachineName: "H5P.FindTheWords",
    h5pAlias: "Find the Words",
    description: "Word search puzzle (page-level only; excluded from compounds).",
    props: [
      { name: "checkId", type: "CheckId", required: true, description: "Stable check id." },
      { name: "words", type: "string[]", required: true, description: "Words to find." },
      { name: "size", type: "number", required: false, description: "Grid size." },
      ...assessmentBehaviourProps,
    ],
    requiredIds: ["checkId"],
    parentConstraints: ["Lesson"],
    a11y: { element: "section", ariaLabel: "Word search", keyboard: "Select letters.", notes: "Not nestable in compounds." },
    theming: { surface: "global-inherit" as const, dataAttributes: ["data-lk-check-id"], stylingNotes: "Uses data-lk-check-id." },
    telemetry: { emits: ["assessment_answered", "assessment_completed"], requiresActiveLesson: true },
  },
  {
    type: "AdventCalendar",
    category: "content" as const,
    h5pMachineName: "H5P.AdventCalendar",
    h5pAlias: "Advent Calendar",
    description: "Calendar with openable doors.",
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "doors", type: "AdventDoor[]", required: true, description: "Calendar doors." },
      { name: "unlockFrom", type: "string", required: false, description: "ISO date to unlock doors." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: [...COMPOUND_PARENTS],
    a11y: { element: "section", ariaLabel: "Advent calendar", keyboard: "Door buttons.", notes: "Optional date gating." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Door grid." },
    telemetry: { emits: ["advent_door_opened"] },
  },
  {
    type: "MapStage",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.GameMap",
    h5pAlias: "Game Map stage",
    description: "Spatial stage in a GameMap with content and exits.",
    allowedChildTypes: [...MAP_STAGE_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.MapStage,
    props: [
      { name: "stageId", type: "string", required: true, description: "Unique stage id." },
      { name: "x", type: "number", required: true, description: "X position percent on map." },
      { name: "y", type: "number", required: true, description: "Y position percent on map." },
      { name: "label", type: "string", required: false, description: "Stage label." },
      { name: "children", type: "ReactNode", required: true, description: "Content and MapExit controls." },
    ],
    requiredIds: [],
    parentConstraints: ["GameMap"],
    a11y: { element: "section", ariaLabel: "Map stage", keyboard: "Map exits are buttons.", notes: "H5P Game Map stage." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Stage panel." },
    telemetry: { emits: ["map_stage_viewed"], requiresActiveLesson: true },
  },
  {
    type: "MapExit",
    category: "content" as const,
    h5pMachineName: "H5P.GameMap",
    h5pAlias: "Game Map exit",
    description: "Transition control linking to a target MapStage.",
    props: [
      { name: "label", type: "string", required: true, description: "Exit label." },
      { name: "targetStageId", type: "string", required: true, description: "Target stage id." },
      { name: "scoreWeight", type: "number", required: false, description: "Optional exit score weight." },
    ],
    requiredIds: [],
    parentConstraints: ["MapStage"],
    a11y: { element: "button", ariaLabel: "Map exit", keyboard: "Activate to travel.", notes: "Radio group pattern." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Exit button." },
    telemetry: { emits: ["map_exit_selected"], requiresActiveLesson: true },
  },
  {
    type: "GameMap",
    category: "container" as const,
    compoundContract: true as const,
    h5pMachineName: "H5P.GameMap",
    h5pAlias: "Game Map",
    description: "Spatial map branching with scored stages.",
    allowedChildTypes: [...GAME_MAP_ALLOWED_CHILD_TYPES],
    maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.GameMap,
    props: [
      { name: "blockId", type: "BlockId", required: true, description: "Stable block id." },
      { name: "title", type: "string", required: true, description: "Map title." },
      { name: "backgroundSrc", type: "string", required: true, description: "Background image URL." },
      { name: "startStageId", type: "string", required: true, description: "Entry stage id." },
      { name: "showMapScore", type: "boolean", required: false, description: "Show visited-path score." },
      { name: "children", type: "MapStage[]", required: true, description: "Map stages." },
    ],
    requiredIds: ["blockId"],
    parentConstraints: ["Lesson"],
    a11y: { element: "section", ariaLabel: "Game map", keyboard: "Map markers and exits.", notes: "H5P Game Map equivalent." },
    theming: { surface: "global-inherit" as const, stylingNotes: "Spatial map." },
    telemetry: { emits: ["map_stage_viewed", "map_exit_selected"], requiresActiveLesson: true },
  },
] satisfies (BlockCatalogEntryV2 & {
  compoundContract?: true;
  allowedChildTypes?: readonly string[];
  maxNestingDepth?: number;
})[];

export function buildV3CatalogFromV2(v2: BlockCatalogEntryV2[]): BlockCatalogEntryV2[] {
  const patched = v2.map((entry) => {
    const base = extendParents(entry);
    if (entry.type === "AssessmentSequence") {
      return {
        ...base,
        compoundContract: true as const,
        allowedChildTypes: [...ASSESSMENT_SEQUENCE_ALLOWED_CHILD_TYPES],
        maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.AssessmentSequence,
      };
    }
    if (entry.type === "SingleChoiceSet") {
      return {
        ...base,
        compoundContract: true as const,
        allowedChildTypes: [...SINGLE_CHOICE_SET_ALLOWED_CHILD_TYPES],
        maxNestingDepth: COMPOUND_MAX_NESTING_DEPTH.SingleChoiceSet,
      };
    }
    return base;
  });
  return [...patched, ...v3CompoundAndContentEntries];
}
