export {
  Course,
  KnowledgeCheck,
  Lesson,
  ProgressTracker,
  Quiz,
  Reflection,
  Scenario,
  /** @deprecated Import from `@lessonkit/react/testing`. */
  resetQuizWarningsForTests,
} from "./components";

export {
  TrueFalse,
  MarkTheWords,
  FillInTheBlanks,
  DragTheWords,
  DragAndDrop,
  AssessmentSequence,
  Text,
  Heading,
  Image,
  Video,
  Page,
  InteractiveBook,
  Slide,
  SlideDeck,
  TimedCue,
  InteractiveVideo,
  Summary,
  ImagePairing,
  ImageSequencing,
  ArithmeticQuiz,
  Essay,
  Questionnaire,
  MemoryGame,
  InformationWall,
  ParallaxSlideshow,
  Accordion,
  DialogCards,
  Flashcards,
  ImageHotspots,
  ImageSlider,
  FindHotspot,
  FindMultipleHotspots,
  BranchingScenario,
  BranchNode,
  BranchChoice,
  Embed,
  Chart,
  Table,
  ImageJuxtaposition,
  Timeline,
  ImageSequence,
  Collage,
  AudioRecorder,
  CombinationLock,
  QrContent,
  Crossword,
  WordSearch,
  AdventCalendar,
  GameMap,
  MapStage,
  MapExit,
} from "./blocks";

export type {
  CourseProps,
  KnowledgeCheckProps,
  LessonProps,
  ProgressTrackerProps,
  QuizProps,
  ReflectionProps,
  ScenarioProps,
} from "./components";

export type {
  TrueFalseProps,
  MarkTheWordsProps,
  FillInTheBlanksProps,
  FillInBlankSpec,
  DragTheWordsProps,
  DragAndDropProps,
  DragItem,
  DropTarget,
  AssessmentSequenceProps,
  TextProps,
  HeadingProps,
  ImageProps,
  PageProps,
  InteractiveBookProps,
  SlideProps,
  SlideDeckProps,
  AccordionProps,
  AccordionSection,
  DialogCardsProps,
  DialogCard,
  FlashcardsProps,
  Flashcard,
  ImageHotspotsProps,
  HotspotSpec,
  ImageSliderProps,
  ImageSlide,
  FindHotspotProps,
  HotspotTarget,
  FindMultipleHotspotsProps,
  BranchingScenarioProps,
  BranchNodeProps,
  BranchChoiceProps,
  EmbedProps,
  ChartProps,
  ChartDatum,
  VideoProps,
  TimedCueProps,
  InteractiveVideoProps,
  SummaryProps,
  ImagePairingProps,
  ImagePair,
  ImageSequencingProps,
  SequencingImage,
  ArithmeticQuizProps,
  ArithmeticProblem,
  EssayProps,
  QuestionnaireProps,
  QuestionnaireField,
  MemoryGameProps,
  MemoryPair,
  InformationWallProps,
  InformationPanel,
  ParallaxSlideshowProps,
  ParallaxSlide,
  TableProps,
  ImageJuxtapositionProps,
  TimelineProps,
  TimelineEvent,
  ImageSequenceProps,
  SequenceFrame,
  CollageProps,
  CollageCell,
  AudioRecorderProps,
  CombinationLockProps,
  QrContentProps,
  CrosswordProps,
  CrosswordEntry,
  WordSearchProps,
  AdventCalendarProps,
  AdventDoor,
  GameMapProps,
  MapStageProps,
  MapExitProps,
} from "./blocks";

export type {
  CompoundHandle,
  CompoundResumeState,
  CompoundBaseProps,
} from "@lessonkit/core";

export {
  useCompletion,
  useLessonkit,
  useProgress,
  useQuizState,
  useAssessmentState,
  useTracking,
} from "./hooks";

/** @deprecated Import from `@lessonkit/react/testing`. */
export { resetAssessmentWarningsForTests } from "./assessment/AssessmentLessonGuard";

export type {
  LessonkitConfig,
  LessonkitObservabilityConfig,
  LessonkitProviderProps,
  LessonkitRuntime,
} from "./context";
export { LessonkitProvider } from "./context";
export { assertProductionCourseConfig, shouldEnforceProductionGuard } from "./runtime/productionGuard";

export type { LmsBridgeMode, McqAssessmentProps } from "@lessonkit/core";

export type {
  AssessmentAnsweredData,
  AssessmentBaseProps,
  AssessmentBehaviour,
  AssessmentCompletedData,
  AssessmentHandle,
  AssessmentInteractionType,
  AssessmentXAPIData,
  AssessmentScoreInput,
  AssessmentScoreResult,
  InteractionBlockRegistration,
  LessonkitPlugin,
  LessonkitPluginContext,
  LessonkitPluginKind,
  PluginHost,
  PluginRegistry,
  TelemetryPipelineSink,
} from "@lessonkit/core";
export {
  buildTelemetryEvent,
  createLessonkitRuntime,
  createPluginRegistry,
  createTelemetryPipeline,
  defineAssessmentPlugin,
  defineLifecyclePlugin,
  defineTelemetryPlugin,
} from "@lessonkit/core";

export type {
  ThemeContextValue,
  ThemeMode,
  ThemeProviderProps,
  ThemeResolvedMode,
} from "./theme/ThemeProvider";
export { ThemeProvider, useTheme } from "./theme/ThemeProvider";
export { useBranchingScenario } from "./compound/useBranchingScenario";
export type { ThemePresetName } from "@lessonkit/themes";

export type {
  BlockCatalogEntry,
  BlockCatalogEntryV2,
  BlockCatalogEntryV3,
  BlockPropSpec,
} from "./blockCatalog";
export {
  BLOCK_CATALOG,
  BLOCK_CATALOG_V2,
  BLOCK_CATALOG_V3,
  blockCatalogVersion,
  blockCatalogV2Version,
  blockCatalogV3Version,
  buildBlockCatalog,
  getBlockCatalogEntry,
} from "./blockCatalog";

