name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    permissions:
      contents: read
      security-events: write
      actions: read

